apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: tour
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaset.replicas }}
  selector:
    matchLabels:
      app: tour
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: tour
        env: {{ .Values.env }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.owner }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.image.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-secret