apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argo
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/HAT-Here-And-There/here-and-there-kubernetes.git
    targetRevision: HEAD
    path: argocd/apps-aws

  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
