---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongodb-secret
spec:
  encryptedData:
    mongo-root-password: AgBExmthvN7hDR7CffBs8gEXb4fyltzhy/afaMkvHHuaSAND9ZqRTE6jCTJgsbec6VXd7c9c1+gFT4MoeFSgChQcbUyGuh9H8W214NSeTfnpAJ28WyFzKydYH3y9bHSlNxCDTC0JMiN20wyX4eyEiP4wqJkqtlnxjonvwrCKKmviqfhRR3yK+DqcBcJhEJFxsnOAHaZ28fc6+rlIXLlimaJ9hBX5Sj7nQKN7ljYYwmm6Ef4CXQUJYJblD/n5kQetMCGCvnhfe08+BZV2HuS54LN+LB/Z+f4wNI0GwiEe1Aq9vQy2Mncsf3nMdiu1BCySAHb3H7REYs8gARBgzK6w7vojTuv3yb64UTB6ICE2Z8wfpccpdKy2Ee9l2ig5SSz/eEJOvWpMTEdlwcshrWj/jhmkqNA/aqAc8mR8PVo6WkPnHVTi5Nd6CVJQBjWWoIQ490Bz2tRcHmlXLq24e8KWvrnB/DOSicIsYqIKfJXmmUWjzjJLWBKD7w7/ds6Opqd/akw73wS9s+W6SHhcFpMx5Y3GVkyzzRBCw8fDXdCvHz1NKDTffalPDV92+mJOQJg1AWILfGgla/wjG8YwKyp/VH4YMWnkS43rDgPohVnCszk+k5Oko9Re9fqK2eiE3JCLzzftjOaEMTBaSNEc7e6Sgh+g8Tgys3DBEVqisb1B+8+3rJVViNFpWjpAEXPE54yklfNUaGEOZAMP5g==
    mongo-root-username: AgA/HC4cLaYAMLgyIldqDdNFmxXm5Lm8viVm6fFNoxnVO/pWsTeWbr6+7jIYd+Jvkrw5W5ONskBLiCwHZ3VSgP+nM0wMIbqrKXvIId2g4Z2WkqcYo52qqSBdvK83ktxSPGablMxBJNbVaMolwTsvJa8S43Gl4q5ObtEtdMbN/TtC15WqBdIUWGq1731ZDquETjf6OE83WG81i6QMkynYsgSwe4zf92Eqwd0ksKwsj7ZjI/0bSgk4Emu6Eu4yO2EEP9Cznfs1YPwrLBrmVvr9/uni8emZgcFDEGNcfwfCGJgB9dz/SgKn4TnW2UaM5E88fIU21nxSeCxWQWzYWICRyFmL7CjSZdAT7YXEAlQCv85kUBmiDuiZOlz0tz/0pwO50ZX4sydnPSn4dilg08E/9atCaeLPS56Mq0TFaaEQ6kAF/hrLk+KhKK+/WqpRVnen0qz0iJEXDesvpGecX3lR1eYZiwwqcB29L/kN77Pz4nu/eS2LiN/UluYV90o8PxuNwIJ3Bq9Ctk5+D1DDxI3JskYguPfjHeV/JE9iZUfyLsIaUV4ZFiDNQvfSXJYAhh0rvkVuESWESr1F5t68HhnCOnH6BDbtQi8pnJlyUkBZ5jrKMwbMbpi12hDLCULOfjByOlFML3JPf4uC3MHU37vhMdwpojfpp2+YqLFwLOE7pzsxTnpk8TQuhHIPDeb/VooCgqAw4v3R
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongodb-secret
    type: Opaque
