apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-noti
data:
  service.webhook.slack_webhook: |
    url: https://hooks.slack.com/services/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
    headers:
    - name: Content-Type
      value: application/json

  template.send-slack: |
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#18be52",
              "fields": [{
                "title": "Sync Status",
                "value": "{{.app.status.sync.status}}",
                "short": true
              }, {
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              }]
            }]
          }
