apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argo
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.webhook.slack_webhook: "개발-관련-알림"
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://github.com/HAT-Here-And-There/here-and-there-kubernetes.git
    targetRevision: main
    path: application-helm/user-service
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
